/**
 * Auto-generated TypeScript types from fmSchema.json
 * Generated by fm-jsdriver schema generator
 * DO NOT EDIT THIS FILE MANUALLY
 */

import { FMSchema } from 'fm-jsdriver';

// Contacts Layout
export interface ContactsFields {
  /** auto-enter, required, type: normal */
  id?: number;
  /** required, type: normal */
  name: string;
  /** type: normal */
  email?: string;
  /** type: normal */
  company?: string;
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  /** auto-enter, type: normal */
  createdAt?: string;
  /** auto-enter, type: normal */
  modifiedAt?: string;
}

export const ContactsPrimaryKey: string[] = ['id'];

// Companies Layout
export interface CompaniesFields {
  /** auto-enter, required, type: normal */
  id?: number;
  /** required, type: normal */
  companyName: string;
  industry?: string;
  website?: string;
  employeeCount?: number;
  revenue?: number;
  founded?: string;
  isActive?: boolean;
}

export const CompaniesPrimaryKey: string[] = ['id'];

// Projects Layout
export interface ProjectsFields {
  /** auto-enter, required, type: normal */
  projectId?: string;
  /** required, type: normal */
  projectName: string;
  description?: string;
  /** required, type: normal */
  startDate: string;
  endDate?: string;
  budget?: number;
  /** required, type: normal */
  status: string;
  clientId?: number;
}

export const ProjectsPrimaryKey: string[] = ['projectId'];

// Invoices Layout
export interface InvoicesFields {
  /** auto-enter, required, type: normal */
  invoiceId?: number;
  /** auto-enter, required, type: normal */
  invoiceNumber?: string;
  /** required, type: normal */
  clientId: number;
  /** required, type: normal */
  issueDate: string;
  /** required, type: normal */
  dueDate: string;
  /** required, type: normal */
  amount: number;
  amountPaid?: number;
  /** required, type: normal */
  status: string;
  notes?: string;
}

export const InvoicesPrimaryKey: string[] = ['invoiceId', 'invoiceNumber'];

// Complete schema export
const fmSchema: FMSchema = {
  "fmSchema": {
    "layouts": {
      "Contacts": {
        "fields": {
          "id": {
            "_meta": {
              "autoEnter": true,
              "notEmpty": true,
              "type": "normal"
            },
            "type": "number"
          },
          "name": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "email": {
            "_meta": {
              "type": "normal"
            },
            "type": "string"
          },
          "company": {
            "_meta": {
              "type": "normal"
            },
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "zip": {
            "type": "string"
          },
          "createdAt": {
            "_meta": {
              "autoEnter": true,
              "type": "normal"
            },
            "type": "timestamp"
          },
          "modifiedAt": {
            "_meta": {
              "autoEnter": true,
              "type": "normal"
            },
            "type": "timestamp"
          }
        }
      },
      "Companies": {
        "fields": {
          "id": {
            "_meta": {
              "autoEnter": true,
              "notEmpty": true,
              "type": "normal"
            },
            "type": "number"
          },
          "companyName": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "industry": {
            "type": "string"
          },
          "website": {
            "type": "string"
          },
          "employeeCount": {
            "type": "number"
          },
          "revenue": {
            "type": "number"
          },
          "founded": {
            "type": "date"
          },
          "isActive": {
            "type": "boolean"
          }
        }
      },
      "Projects": {
        "fields": {
          "projectId": {
            "_meta": {
              "autoEnter": true,
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "projectName": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "startDate": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "date"
          },
          "endDate": {
            "type": "date"
          },
          "budget": {
            "type": "number"
          },
          "status": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "clientId": {
            "type": "number"
          }
        }
      },
      "Invoices": {
        "fields": {
          "invoiceId": {
            "_meta": {
              "autoEnter": true,
              "notEmpty": true,
              "type": "normal"
            },
            "type": "number"
          },
          "invoiceNumber": {
            "_meta": {
              "autoEnter": true,
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "clientId": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "number"
          },
          "issueDate": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "date"
          },
          "dueDate": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "date"
          },
          "amount": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "number"
          },
          "amountPaid": {
            "type": "number"
          },
          "status": {
            "_meta": {
              "notEmpty": true,
              "type": "normal"
            },
            "type": "string"
          },
          "notes": {
            "type": "string"
          }
        }
      }
    }
  }
} as const;

export default fmSchema;
