#!/usr/bin/env node

/**
 * CLI tool to generate TypeScript types from fmSchema.json
 * Usage: npx fm-generate-schema [input-file] [output-file]
 * Default: npx fm-generate-schema fmSchema.json fmSchema.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { FMSchema, LayoutDefinition } from './types';
import { validateSchema, getPrimaryKeyFields } from './schema';

/**
 * Converts FileMaker field type to TypeScript type
 */
function mapTypeToTS(fieldType: string): string {
  const typeMap: Record<string, string> = {
    'string': 'string',
    'text': 'string',
    'number': 'number',
    'date': 'string',
    'time': 'string',
    'timestamp': 'string',
    'boolean': 'boolean',
    'container': 'string'
  };

  return typeMap[fieldType.toLowerCase()] || 'any';
}

/**
 * Generates TypeScript interface for a layout
 */
function generateLayoutInterface(layoutName: string, layout: LayoutDefinition): string {
  const interfaceName = `${layoutName}Fields`;
  const fields = layout.fields;

  let interfaceCode = `export interface ${interfaceName} {\n`;

  for (const [fieldName, field] of Object.entries(fields)) {
    const tsType = mapTypeToTS(field.type);
    const isRequired = field._meta?.notEmpty && !field._meta?.autoEnter;
    const optional = isRequired ? '' : '?';

    // Add JSDoc comment with metadata
    if (field._meta) {
      interfaceCode += `  /** `;
      const meta: string[] = [];
      if (field._meta.autoEnter) meta.push('auto-enter');
      if (field._meta.notEmpty) meta.push('required');
      if (field._meta.type) meta.push(`type: ${field._meta.type}`);
      interfaceCode += meta.join(', ');
      interfaceCode += ` */\n`;
    }

    interfaceCode += `  ${fieldName}${optional}: ${tsType};\n`;
  }

  interfaceCode += `}\n`;

  return interfaceCode;
}

/**
 * Generates primary key constants for each layout
 */
function generatePrimaryKeyConstants(layoutName: string, layout: LayoutDefinition): string {
  const primaryKeys = getPrimaryKeyFields(layout);

  if (primaryKeys.length === 0) {
    return `export const ${layoutName}PrimaryKey: string[] = [];\n`;
  }

  return `export const ${layoutName}PrimaryKey: string[] = [${primaryKeys.map(k => `'${k}'`).join(', ')}];\n`;
}

/**
 * Generates the complete TypeScript file from schema
 */
function generateTypeScriptFromSchema(schema: FMSchema): string {
  let output = `/**
 * Auto-generated TypeScript types from fmSchema.json
 * Generated by fm-jsdriver schema generator
 * DO NOT EDIT THIS FILE MANUALLY
 */

import { FMSchema } from 'fm-jsdriver';

`;

  // Generate interfaces for each layout
  const layouts = schema.fmSchema.layouts;

  for (const [layoutName, layout] of Object.entries(layouts)) {
    output += `// ${layoutName} Layout\n`;
    output += generateLayoutInterface(layoutName, layout);
    output += '\n';
    output += generatePrimaryKeyConstants(layoutName, layout);
    output += '\n';
  }

  // Generate the schema export
  output += `// Complete schema export\n`;
  output += `const fmSchema: FMSchema = ${JSON.stringify(schema, null, 2)} as const;\n\n`;
  output += `export default fmSchema;\n`;

  return output;
}

/**
 * Main execution function
 */
function main() {
  const args = process.argv.slice(2);
  const inputFile = args[0] || 'fmSchema.json';
  const outputFile = args[1] || 'fmSchema.ts';

  // Resolve paths relative to current working directory
  const inputPath = path.resolve(process.cwd(), inputFile);
  const outputPath = path.resolve(process.cwd(), outputFile);

  console.log(`Reading schema from: ${inputPath}`);

  // Read and parse input file
  if (!fs.existsSync(inputPath)) {
    console.error(`Error: Input file not found: ${inputPath}`);
    console.error(`\nPlease create a fmSchema.json file or specify the correct path.`);
    process.exit(1);
  }

  let schema: any;
  try {
    const fileContent = fs.readFileSync(inputPath, 'utf-8');
    schema = JSON.parse(fileContent);
  } catch (error) {
    console.error(`Error reading or parsing input file: ${error}`);
    process.exit(1);
  }

  // Validate schema
  try {
    validateSchema(schema);
  } catch (error) {
    console.error(`Schema validation error: ${error}`);
    process.exit(1);
  }

  // Generate TypeScript code
  const tsCode = generateTypeScriptFromSchema(schema);

  // Write output file
  try {
    fs.writeFileSync(outputPath, tsCode, 'utf-8');
    console.log(`✓ Successfully generated TypeScript types at: ${outputPath}`);
  } catch (error) {
    console.error(`Error writing output file: ${error}`);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main();
}

export { generateTypeScriptFromSchema, generateLayoutInterface, generatePrimaryKeyConstants };
