/**
 * fm-jsDriver: Type-safe FileMaker driver for webviewer communication
 * Main driver implementation using fm-gofer for FileMaker script execution
 */

import {
  FMSchema,
  LayoutMethods,
  ScriptInput,
  ScriptObject,
  FindOptions,
  DriverParameter,
  Driver
} from './types';
import { validateSchema, getLayoutNames } from './schema';

// Import FMGofer - this should be available in the browser context
declare const FMGofer: {
  PerformScript(scriptName: string, parameter: string): Promise<any>;
};

/**
 * Normalizes ScriptInput to ScriptObject format
 */
function normalizeScript(script: ScriptInput | undefined): ScriptObject | undefined {
  if (!script) {
    return undefined;
  }

  if (typeof script === 'string') {
    return {
      script: script,
      parameter: '',
      option: 0
    };
  }

  return script;
}

/**
 * Executes a FileMaker operation via FMGofer.PerformScript
 */
async function executeFileMakerOperation(parameter: DriverParameter): Promise<any> {
  try {
    // Check if FMGofer is available
    if (typeof FMGofer === 'undefined') {
      throw new Error('FMGofer is not available. Ensure you are running in a FileMaker webviewer context.');
    }

    // Convert parameter to JSON string
    const parameterJson = JSON.stringify(parameter);

    // Execute via FMGofer
    const result = await FMGofer.PerformScript('jsDriver', parameterJson);

    // Parse result if it's a string
    if (typeof result === 'string') {
      try {
        return JSON.parse(result);
      } catch {
        return result;
      }
    }

    return result;
  } catch (error) {
    throw new Error(`FileMaker operation failed: ${error}`);
  }
}

/**
 * Creates layout-specific methods for CRUD operations
 */
function createLayoutMethods<T>(layoutName: string): LayoutMethods<T> {
  return {
    /**
     * Creates a new record
     * Primary keys are auto-generated by FileMaker
     */
    async create(
      fieldData: T,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      const parameter: DriverParameter = {
        dapi: {
          action: 'create',
          layouts: layoutName,
          fieldData: fieldData as Record<string, any>,
          dateformats: 2
        }
      };

      // Add prescript if provided
      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      // Add script if provided
      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    },

    /**
     * Updates an existing record by recordId
     */
    async update(
      recordId: string | number,
      fieldData: Partial<T>,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      const parameter: DriverParameter = {
        dapi: {
          action: 'update',
          layouts: layoutName,
          recordId: recordId,
          fieldData: fieldData as Record<string, any>,
          dateformats: 2
        }
      };

      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    },

    /**
     * Retrieves a single record by recordId
     */
    async get(
      recordId: string | number,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      const parameter: DriverParameter = {
        dapi: {
          action: 'read',
          layouts: layoutName,
          recordId: recordId,
          dateformats: 2
        }
      };

      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    },

    /**
     * Finds records matching query criteria
     */
    async find(
      query: Partial<T>,
      options?: FindOptions,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      // Convert query object to FileMaker query format
      const fmQuery: Array<Record<string, string>> = [
        Object.keys(query).reduce((acc, key) => {
          acc[key] = String((query as any)[key]);
          return acc;
        }, {} as Record<string, string>)
      ];

      const parameter: DriverParameter = {
        dapi: {
          action: 'read',
          layouts: layoutName,
          query: fmQuery,
          ...(options?.offset !== undefined && { offset: options.offset }),
          ...(options?.limit !== undefined && { limit: options.limit }),
          dateformats: 2
        }
      };

      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    },

    /**
     * Lists all records with optional pagination
     */
    async list(
      options?: FindOptions,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      const parameter: DriverParameter = {
        dapi: {
          action: 'read',
          layouts: layoutName,
          ...(options?.offset !== undefined && { offset: options.offset }),
          ...(options?.limit !== undefined && { limit: options.limit }),
          dateformats: 2
        }
      };

      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    },

    /**
     * Deletes a record by recordId
     */
    async delete(
      recordId: string | number,
      prescript?: ScriptInput,
      script?: ScriptInput
    ): Promise<any> {
      const parameter: DriverParameter = {
        dapi: {
          action: 'delete',
          layouts: layoutName,
          recordId: recordId,
          dateformats: 2
        }
      };

      if (prescript) {
        parameter.prescript = normalizeScript(prescript);
      }

      if (script) {
        parameter.script = normalizeScript(script);
      }

      return executeFileMakerOperation(parameter);
    }
  };
}

/**
 * Creates the main driver with layout-specific methods
 */
export function createDriver(schema: FMSchema): Driver {
  // Validate schema
  validateSchema(schema);

  // Get all layout names
  const layoutNames = getLayoutNames(schema);

  // Create driver object
  const driver: any = {
    /**
     * Executes a custom FileMaker script without layout context
     */
    executeScript: async (script: ScriptInput): Promise<any> => {
      const parameter: DriverParameter = {
        script: normalizeScript(script)
      };

      return executeFileMakerOperation(parameter);
    }
  };

  // Add layout-specific methods
  for (const layoutName of layoutNames) {
    driver[layoutName] = createLayoutMethods(layoutName);
  }

  return driver as Driver;
}

// Export all types for use by consumers
export * from './types';
export * from './schema';
export { generateTypeScriptFromSchema } from './generator';
